blank_issues_enabled: false
contact_links:
  - name: Suggestion
    url: https://github.com/Roadhog360/Et-Futurum-Requiem/discussions
    about: >-
      Click here if you want to post a suggestion instead of reporting a bug.
  - name: Legacy Modding Discord
    url: https://discord.gg/EXshrPV
    about: >-
      The Discord channel that houses channels for Et Futurum Requiem and is your one-stop-shop for any legacy version between 1.3 up to the latest unsupported version.
